### PR TITLE
Update main.lua

### PR DESCRIPTION
**Pull request by amgmacht**
fix that create character is displayed all the time

### CODE REVIEW

**Comment by AfterLifeStudio** [comment]
create character should be disabled after the limit is reached

**Comment by amgmacht** [comment]
> create character should be disabled after the limit is reached
> 
> 

When I wrote in Config.Slots = 1 I still had the problem that he showed me the window Create Character and always counted + 1 slot that is he always showed it after I made it away it worked great and also tested it more meals with several people.

**Comment by amgmacht** [comment]
> create character should be disabled after the limit is reached
> 
> 

And so the create button will only show up if you have 2 or more entered in the multicharacter_slots table, since most only want one character for their players and the teamers can then create 2 or more.

So the fix for me I think many others would like it too which is why I did it that way.

**Comment by amgmacht** [comment]
But with your default code the display is always shown when you are under 5 characters even after each create the display does not turn off until you have 5 or more. That's why I solved it this way.

I use ( esx_legacy 1.10.1 )

**Pull request merged**
